### ISSUE TITLE
Reading view

### ISSUE THREAD

**Issue by gapmiss** [imshenshen/obsidian-sticky-heading#1]
Trying out your new plugin.

Works great in `source` mode and `live preview` mode.

However, it does not appear to work in the `reading` view.

Is the plugin intended to work in `reading` view?

**Comment by imshenshen** [comment]
I'm not going to implement it in reading view. 

This plugin mainly aims to solve the problem of: when writing in fragmented time, I often forget which heading level I am currently at, or which level I should use for the next heading.

The obsidian's core plugin `Outline` is good enough when reading.

**Comment by imshenshen** [comment]
Its now on Obsidian's community plugins, you can search and install.

**Comment by FAL0258** [comment]
We need this to be available in live preview mode too!
This plugin is super helpful, given the existence of core plugin!
