### ISSUE TITLE
yea this is great... how come it's not on the Community Plugins Browser?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [imshenshen/obsidian-sticky-heading#3]
This is exactly what I was looking for, coming over from Logseq there is a beautiful plugin that does exactly this is, and it's one of my favorite so it's nice knowing I can have it here too on Obsidian.

* https://github.com/yoyurec/logseq-sticky-headers

Thanks again!!

p.s. - i add to update the css because there was some overlap issue with Minimal theme

```
.obsidian-sticky-heading {
height: 60px;
line-height: 60px;
}
```

also it might not be a bad idea to add in plugin options to "hide" or "disable" the .obsidian-sticky-heading

**Comment by imshenshen** [comment]
* Is now on community plugins.
* I can use runtime javascript to make it better , but:
    > When the heading is sticky, we may change its appearance, but this will lead to additional computation and performance consumption. For the sake of performance and simplicity, we have retained its original style.
