### ISSUE TITLE
[FR] Show all parent headings of all levels above cuurent text

### ISSUE THREAD

**Issue by a13ph** [imshenshen/obsidian-sticky-heading#4]
E.g. if user is reading (as per topmost visible line) a text under heading2, show as sticky both heading1 and heading2

**Comment by DanShui-Yu** [comment]
I encountered the same issue.

![image](https://github.com/imshenshen/obsidian-sticky-heading/assets/69069739/4f305de2-7dc8-4c1d-a142-f278bf43ff1c)

**Comment by imshenshen** [comment]
> I encountered the same issue.
> 
> ![image](https://private-user-images.githubusercontent.com/69069739/316321142-4f305de2-7dc8-4c1d-a142-f278bf43ff1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTYwNDUsIm5iZiI6MTcxMTI5NTc0NSwicGF0aCI6Ii82OTA2OTczOS8zMTYzMjExNDItNGYzMDVkZTItN2RjOC00YzFkLWExNDItZjI3OGJmNDNmZjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE1NTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExODI4OWE4MWYyZDM5ZjdlMWVjZGMwOGY1YzlhMzk1ODZkODViNGE5ZmUyZmY3NjdkNWM3NjgyYjhmM2U2NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0oMzgG2ssA-7s8b68nRGzlC-LAGl0ACeOOqhdI8UlmM)

the CSS position:sticky is setting to all headings and use Obsidian's css var `--titlebar-background` as background. It seems that the theme or custom CSS you are using sets `--titlebar-background` to be transparent. You can try to check the value of --titlebar-background and set a reasonable color in the theme or elsewhere.

If there are too many problems that cannot be avoided by default, I would consider using runtime javascript to set which heading should be sticky, and the style when it is set to sticky.

**Comment by a13ph** [comment]
I am not reporting this as an issue, it's a feature request

**Comment by Benature** [comment]
> E.g. if user is reading (as per topmost visible line) a text under heading2, show as sticky both heading1 and heading2

Looking forward to this feature too!

**Comment by a13ph** [comment]
Thanks, I can confirm that this feature is working as expected, if beta is installed via BRAT and feature is enabled in plugin options


![image](https://github.com/imshenshen/obsidian-sticky-heading/assets/577817/c019d2a3-3688-41b4-b0ef-f56792e4ffa3)
