### ISSUE TITLE
Using backticks in a heading cuts off displayed text

### ISSUE THREAD

**Issue by a13ph** [imshenshen/obsidian-sticky-heading#7]
```
# first `second` third
```

will be displayed as

```
third
```

**Comment by merlinuwe** [comment]
Thanks for this update, which I have installed.

I have a similar issue on android 11 (Xiaomi Poco X3 Pro) with dataview expressions, which are not evaluated.

```
### 1.3 Klassenarbeiten (`=this.KA_Anzahl`)
```
![image](https://github.com/imshenshen/obsidian-sticky-heading/assets/4138869/2a164fe7-c81a-4ec4-a224-06b1c885345a)

The same is visible on windows 11.

![image](https://github.com/imshenshen/obsidian-sticky-heading/assets/4138869/853837c8-c56e-4003-a183-e2cba74e6eab)

--

Here on windows, the text covers an other element (from note toolbar plugin) at the top area.

**Comment by imshenshen** [comment]
> Thanks for this update, which I have installed.
> 
> I have a similar issue on android 11 (Xiaomi Poco X3 Pro) with dataview expressions, which are not evaluated.
> 
> ```
> ### 1.3 Klassenarbeiten (`=this.KA_Anzahl`)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/4138869/324841322-2a164fe7-c81a-4ec4-a224-06b1c885345a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTQyNTIsIm5iZiI6MTcxMzk1Mzk1MiwicGF0aCI6Ii80MTM4ODY5LzMyNDg0MTMyMi0yYTE2NGZlNy1jODFhLTRlYzQtYTIyNC0wNmIxYzg4NTM0NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMTAxOTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjNhNjhkZWI4ZDU2ZDNkYjU4ZDE3YWRlN2M2Zjg0OWVmZTI2MTkzZjVjOGQzODYyODY1OTgyMzFmYzA3YTNjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bvQhMUxpr1oTR-i5_pd2USQZ-RVNQLJYxzyKExm7ubg)
> 
> The same is visible on windows 11.
> 
> ![image](https://private-user-images.githubusercontent.com/4138869/324842725-853837c8-c56e-4003-a183-e2cba74e6eab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTQyNTIsIm5iZiI6MTcxMzk1Mzk1MiwicGF0aCI6Ii80MTM4ODY5LzMyNDg0MjcyNS04NTM4MzdjOC1jNTZlLTQwMDMtYTE4My1lMmNiYTc0ZTZlYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMTAxOTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRiY2Q5ZmNkZGRjOTg3MTMyOWMyNTVmZGYwYmM1OGI0YmI3NGQyOTdkN2M2MmRjMWFhYzc5YjU4OWU4OGE4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kzISK67THlmqDDqbHrbSWNSh-51Ymofo22zwextkPDc)
> 
> --
> 
> Here on windows, the text covers an other element (from note toolbar plugin) at the top area.

1. Using `MarkdownRenderer` to render sticky headings is the best way for now. I think it can't render all custom markdown mark.
2. Other plugin may add elements to the DOM, I will add a setting to config `topMargin` of sticky heading container
3. Sticky heading container use css var `--file-line-width` or `--line-width`, the image you posted doesn't seem to make the container as wide as the document. If we add the `topMargin` configuration, I'm not sure what the result will be.
